name: integration

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'dist/**'
      - 'src/**'
      - 'action.yml'
      - 'yarn.lock'

jobs:
  e2e:
    name: End-to-end test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
